### PR TITLE
Fix running the rails generator inside the extension

### LINKED ISSUE #86: bin/rails generators only run in sandbox
when running the rails generators they are run inside the sandbox, this means we have to copy/paste generated files like migrations etc from the sandbox up to the extension root path. 

We should document this, but maybe add another option to have this run inside the extension path?

### PR DESCRIPTION
**Pull request by peterberkenbosch**
Since extensions are engines, my expectation would be that the `bin/rails` command is working like in a rails engine as well. This way I can generate my migrations, models etc. This is a Rails convention as well. Also see https://guides.rubyonrails.org/engines.html#bin-directory

Fixes #86 

## Summary

Reverting bin/rails to be the conventional command as a rails engine, this is breaking the specs right now since we cannot run bin/sandbox directly.

- [x] `bin/rails` updated -> renamed to `bin/r`
- [x] fix sandbox generation and related specs.
- [x] introduce `bin/sandbox_rails` executable that runs the rails exec inside the sandbox

## Checklist

- [x] I have structured the commits for clarity and conciseness.
- [x] I have added relevant automated tests for this change.
- [x] I have added an entry to the changelog for this change.

### CODE REVIEW

**Comment by peterberkenbosch** [comment]
@elia @aldesantis any idea why this only works when we call the binary 'rails'? All attempts to work around it fails for me. I really think we should not run bin/rails in the sandbox, but keep the Rails Engine conventions. That part actually works, we can generate migrations etc in the root of the extension. Thoughts?

File: lib/solidus_dev_support/templates/extension/lib/%file_name%/engine.rb.tt [hunk 1]
```diff
@@ -1,6 +1,7 @@
 # frozen_string_literal: true
 
 require 'spree/core'
+require '<%=file_name %>'
```
Comment (elia) [inline lib/solidus_dev_support/templates/extension/lib/%file_name%/engine.rb.tt]: nit: missing space

File: spec/features/create_extension_spec.rb [hunk 2]
```diff
@@ -101,7 +101,7 @@ def check_run_specs
 
   def check_sandbox
     cd(install_path) do
-      command = 'bin/rails runner "puts %{The version of SolidusTestExtension is #{SolidusTestExtension::VERSION}}"'
+      command = 'bin/test_app runner "puts %{The version of SolidusTestExtension is #{SolidusTestExtension::VERSION}}"'
```
Comment (elia) [inline spec/features/create_extension_spec.rb]: This should be something other than "test_app", the sandbox was introduced precisely to avoid using the test_app for direct development and experimentation, leaving it just as a test dummy. So `bin/dev_app` or `bin/sandbox-rails` might be better names.

**Comment by elia** [comment]
> @elia @aldesantis any idea why this only works when we call the binary 'rails'? All attempts to work around it fails for me. I really think we should not run bin/rails in the sandbox, but keep the Rails Engine conventions. That part actually works, we can generate migrations etc in the root of the extension. Thoughts?

@peterberkenbosch I didn't know about the rails conventions (TMYK!), the main drive for targeting bin/rails at the sanbox was to allow `bin/rails server` to start something that can be used for development. So I'm wondering if we can have the best of both worlds.

Digging into some rails code it's also worth mentioning that `rails/engine/commands.rb` doesn't do much more than setting the APP_PATH to the `test/dummy` unless it's already present.

https://github.com/rails/rails/blob/master/railties/lib/rails/engine/commands.rb

Apparently it's enough to define ENGINE_ROOT and ENGINE_PATH in order to make generators operate on the extension instead of forwarding to the app, so maybe we can just do that.

**Comment by peterberkenbosch** [comment]
@elia Yes, that's what I was doing here with the bin/rails command, adding the proper constants and loading the generator files. I'll try renaming the test_app command again.

**Comment by peterberkenbosch** [comment]
can't make it work, can't wrap my head around this tbh..

keep getting:

```
CommandFailed:
       command failed: bin/sandbox_rails runner "puts %{The version of SolidusTestExtension is #{SolidusTestExtension::VERSION}}"
       Creating the sandbox app...
       Can't initialize a new Rails application within the directory of another, please change to a non-Rails directory first.
       Type 'rails' for help.
       sandbox rails application failed
       Automatic creation of the sandbox app failed
```

it works correctly when the script name is `rails` though. So confusing. Trying something else.

**Comment by peterberkenbosch** [comment]
Figured it out, the rails command is looking for a binary called rails in a parent directory. (ie. renaming the `bin/rails` to `bin/rr` for example makes it work. Experimenting a bit more to find the best setting and naming here to finish this one.

**Comment by peterberkenbosch** [comment]
Figured it out, the rails command is looking for a binary called rails in a parent directory. (ie. renaming the `bin/rails` to `bin/rr` for example makes it work. Experimenting a bit more to find the best setting and naming here to finish this one.

**Comment by peterberkenbosch** [comment]
Rebasing this PR right now with additional documentation.

**Comment by peterberkenbosch** [comment]
@elia whenever you have a moment, this one is ready for another pass. Think this is good to go, but curious to see what your opinion is. Thanks!! 💌
